project:
  type: website

website:
  title: "Tyerell Dotson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.pdf
        text: Resume
      - href: projects.qmd
        text: Projects
      - text: Assignments
        menu:
        - href: assign01.qmd
          text: Assignment 1
        - href: podreflection.qmd
          text: Podcast Reflection - DataFramed
        - href: assign02.qmd
          text: Assignment 2
        - href: assign03.qmd
          text: Assignment 3
        - href: assign04.qmd
          text: Assignment 4
        - href: assign05.qmd
          text: Assignment 5
        - href: assign06.qmd
          text: Assignment 6

resources:
  - "Data/govinfo_foreign_relations/pdfs/*"
  
format:
  html:
    theme:
      - paper
      - brand
    css: styles.css
    toc: true

editor: visual

